### PR TITLE
fix(mangademon): rewrite most of the source to account for a site remake

### LINKED ISSUE #753: Manga Demon app source not working
I’m not sure what else to say but the website works just fine but something is wrong with the source in app.

### PR DESCRIPTION
**Pull request by AlokSwaminathan**
Checklist:
- [x] Updated source's version for individual source changes
- [x] Updated all sources' versions for template changes
- [x] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device 

Closes #753

### CODE REVIEW

File: src/rust/en.mangademon/src/parser.rs [hunk 1]
```diff
@@ -61,122 +98,104 @@ pub fn parse_manga_list(html: Node, searching: bool) -> MangaPageResult {
...
-				rating = MangaContentRating::Suggestive;
-			}
-			if categories.iter().any(|e| e == "Smut") {
-				rating = MangaContentRating::Nsfw;
+		for genre in categories.iter() {
+			match genre.to_lowercase().trim() {
+				"Ecchi" | "Harem" | "Mature" => rating = MangaContentRating::Suggestive,
+				"Smut" => rating = MangaContentRating::Nsfw,
+				_ => {}
 			}
```
Comment (Skittyblock) [inline src/rust/en.mangademon/src/parser.rs:149]: you're matching a lowercase string against stuff with capitals, so it'll always fail

also should probably `break` after setting the nsfw rating, because it could loop again and set the rating to suggestive instead of nsfw like it should be
```suggestion
			match genre.to_lowercase().trim() {
				"ecchi" | "harem" | "mature" => rating = MangaContentRating::Suggestive,
				"smut" => {
					rating = MangaContentRating::Nsfw;
					break;
				}
				_ => {}
			}
```

**Review by Skittyblock — CHANGES_REQUESTED** [review]

File: src/rust/en.mangademon/src/parser.rs [hunk 2]
```diff
@@ -61,122 +98,107 @@ pub fn parse_manga_list(html: Node, searching: bool) -> MangaPageResult {
...
 		categories,
+		description,
+		author,
+		artist,
 		status,
 		nsfw,
+		cover,
 		viewer,
+		url: manga_url,
 		..Default::default()
```
Comment (Skittyblock) [inline src/rust/en.mangademon/src/parser.rs:174]: there's a clippy warning here since this isn't necessary
```suggestion
```

**Review by Skittyblock — CHANGES_REQUESTED** [review]
seeing a crash when opening martial peak due to duplicate chapter identifiers. double check how you're assigning chapter ids and make sure they're unique, and make sure to test on device

**Comment by AlokSwaminathan** [comment]
> seeing a crash when opening martial peak due to duplicate chapter identifiers. double check how you're assigning chapter ids and make sure they're unique, and make sure to test on device

I've been reading from mangademon with this version of the source for a few weeks, I have 60 from it and I haven't noticed any issues. What chapter on martial peak are you having problems with, I tested a few chapters on there and they seem to work for me.

**Comment by Skittyblock** [comment]
interestingly enough, it's only happening when run on the simulator. none of the images load for me on device though. the culprit for martial peak is `/chaptered.php?manga=1&chapter=3705`, which I can see on the site is listed twice. this is their mistake, but you should probably filter out duplicates on our end within the source

**Comment by AlokSwaminathan** [comment]
I took a look at 3705 and it seems to work on my phone even though there were chapters with that number. I just went ahead and removed duplicates anyway though

**Review by Skittyblock — APPROVED** [review]
